spring:
  mvc:
    hiddenmethod:
      filter:
        enabled=true:
  profiles:
    active: local
  main:
    banner-mode: off
  h2.console:
    path: '/console'
    enabled: true
  datasource:
    url: 'jdbc:h2:file:./learning-db'
  jpa:
    hibernate:
      ddl-auto: update


